/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeekendLibraryOfLostFortunesRouteImport } from './routes/weekend/library-of-lost-fortunes'
import { Route as WeekendElectricHumOfCuriousPeopleRouteImport } from './routes/weekend/electric-hum-of-curious-people'
import { Route as Weekend48HoursInKigaliRouteImport } from './routes/weekend/48-hours-in-kigali'
import { Route as InvestigationsGreatEthiopianDamNegotiationsRouteImport } from './routes/investigations/great-ethiopian-dam-negotiations'
import { Route as InvestigationsDangoteEffectRefineryRouteImport } from './routes/investigations/dangote-effect-refinery'
import { Route as BriefTheRefineryThatCouldRewireAfricanFinanceRouteImport } from './routes/brief/the-refinery-that-could-rewire-african-finance'
import { Route as BriefSignalFromTheStreetRouteImport } from './routes/brief/signal-from-the-street'
import { Route as BriefEastAfricaInfrastructureParadoxRouteImport } from './routes/brief/east-africa-infrastructure-paradox'
import { Route as BriefAfricanBondMarkets2026RouteImport } from './routes/brief/african-bond-markets-2026'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendLibraryOfLostFortunesRoute =
  WeekendLibraryOfLostFortunesRouteImport.update({
    id: '/weekend/library-of-lost-fortunes',
    path: '/weekend/library-of-lost-fortunes',
    getParentRoute: () => rootRouteImport,
  } as any)
const WeekendElectricHumOfCuriousPeopleRoute =
  WeekendElectricHumOfCuriousPeopleRouteImport.update({
    id: '/weekend/electric-hum-of-curious-people',
    path: '/weekend/electric-hum-of-curious-people',
    getParentRoute: () => rootRouteImport,
  } as any)
const Weekend48HoursInKigaliRoute = Weekend48HoursInKigaliRouteImport.update({
  id: '/weekend/48-hours-in-kigali',
  path: '/weekend/48-hours-in-kigali',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsGreatEthiopianDamNegotiationsRoute =
  InvestigationsGreatEthiopianDamNegotiationsRouteImport.update({
    id: '/investigations/great-ethiopian-dam-negotiations',
    path: '/investigations/great-ethiopian-dam-negotiations',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvestigationsDangoteEffectRefineryRoute =
  InvestigationsDangoteEffectRefineryRouteImport.update({
    id: '/investigations/dangote-effect-refinery',
    path: '/investigations/dangote-effect-refinery',
    getParentRoute: () => rootRouteImport,
  } as any)
const BriefTheRefineryThatCouldRewireAfricanFinanceRoute =
  BriefTheRefineryThatCouldRewireAfricanFinanceRouteImport.update({
    id: '/brief/the-refinery-that-could-rewire-african-finance',
    path: '/brief/the-refinery-that-could-rewire-african-finance',
    getParentRoute: () => rootRouteImport,
  } as any)
const BriefSignalFromTheStreetRoute =
  BriefSignalFromTheStreetRouteImport.update({
    id: '/brief/signal-from-the-street',
    path: '/brief/signal-from-the-street',
    getParentRoute: () => rootRouteImport,
  } as any)
const BriefEastAfricaInfrastructureParadoxRoute =
  BriefEastAfricaInfrastructureParadoxRouteImport.update({
    id: '/brief/east-africa-infrastructure-paradox',
    path: '/brief/east-africa-infrastructure-paradox',
    getParentRoute: () => rootRouteImport,
  } as any)
const BriefAfricanBondMarkets2026Route =
  BriefAfricanBondMarkets2026RouteImport.update({
    id: '/brief/african-bond-markets-2026',
    path: '/brief/african-bond-markets-2026',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brief/african-bond-markets-2026': typeof BriefAfricanBondMarkets2026Route
  '/brief/east-africa-infrastructure-paradox': typeof BriefEastAfricaInfrastructureParadoxRoute
  '/brief/signal-from-the-street': typeof BriefSignalFromTheStreetRoute
  '/brief/the-refinery-that-could-rewire-african-finance': typeof BriefTheRefineryThatCouldRewireAfricanFinanceRoute
  '/investigations/dangote-effect-refinery': typeof InvestigationsDangoteEffectRefineryRoute
  '/investigations/great-ethiopian-dam-negotiations': typeof InvestigationsGreatEthiopianDamNegotiationsRoute
  '/weekend/48-hours-in-kigali': typeof Weekend48HoursInKigaliRoute
  '/weekend/electric-hum-of-curious-people': typeof WeekendElectricHumOfCuriousPeopleRoute
  '/weekend/library-of-lost-fortunes': typeof WeekendLibraryOfLostFortunesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brief/african-bond-markets-2026': typeof BriefAfricanBondMarkets2026Route
  '/brief/east-africa-infrastructure-paradox': typeof BriefEastAfricaInfrastructureParadoxRoute
  '/brief/signal-from-the-street': typeof BriefSignalFromTheStreetRoute
  '/brief/the-refinery-that-could-rewire-african-finance': typeof BriefTheRefineryThatCouldRewireAfricanFinanceRoute
  '/investigations/dangote-effect-refinery': typeof InvestigationsDangoteEffectRefineryRoute
  '/investigations/great-ethiopian-dam-negotiations': typeof InvestigationsGreatEthiopianDamNegotiationsRoute
  '/weekend/48-hours-in-kigali': typeof Weekend48HoursInKigaliRoute
  '/weekend/electric-hum-of-curious-people': typeof WeekendElectricHumOfCuriousPeopleRoute
  '/weekend/library-of-lost-fortunes': typeof WeekendLibraryOfLostFortunesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brief/african-bond-markets-2026': typeof BriefAfricanBondMarkets2026Route
  '/brief/east-africa-infrastructure-paradox': typeof BriefEastAfricaInfrastructureParadoxRoute
  '/brief/signal-from-the-street': typeof BriefSignalFromTheStreetRoute
  '/brief/the-refinery-that-could-rewire-african-finance': typeof BriefTheRefineryThatCouldRewireAfricanFinanceRoute
  '/investigations/dangote-effect-refinery': typeof InvestigationsDangoteEffectRefineryRoute
  '/investigations/great-ethiopian-dam-negotiations': typeof InvestigationsGreatEthiopianDamNegotiationsRoute
  '/weekend/48-hours-in-kigali': typeof Weekend48HoursInKigaliRoute
  '/weekend/electric-hum-of-curious-people': typeof WeekendElectricHumOfCuriousPeopleRoute
  '/weekend/library-of-lost-fortunes': typeof WeekendLibraryOfLostFortunesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brief/african-bond-markets-2026'
    | '/brief/east-africa-infrastructure-paradox'
    | '/brief/signal-from-the-street'
    | '/brief/the-refinery-that-could-rewire-african-finance'
    | '/investigations/dangote-effect-refinery'
    | '/investigations/great-ethiopian-dam-negotiations'
    | '/weekend/48-hours-in-kigali'
    | '/weekend/electric-hum-of-curious-people'
    | '/weekend/library-of-lost-fortunes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brief/african-bond-markets-2026'
    | '/brief/east-africa-infrastructure-paradox'
    | '/brief/signal-from-the-street'
    | '/brief/the-refinery-that-could-rewire-african-finance'
    | '/investigations/dangote-effect-refinery'
    | '/investigations/great-ethiopian-dam-negotiations'
    | '/weekend/48-hours-in-kigali'
    | '/weekend/electric-hum-of-curious-people'
    | '/weekend/library-of-lost-fortunes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brief/african-bond-markets-2026'
    | '/brief/east-africa-infrastructure-paradox'
    | '/brief/signal-from-the-street'
    | '/brief/the-refinery-that-could-rewire-african-finance'
    | '/investigations/dangote-effect-refinery'
    | '/investigations/great-ethiopian-dam-negotiations'
    | '/weekend/48-hours-in-kigali'
    | '/weekend/electric-hum-of-curious-people'
    | '/weekend/library-of-lost-fortunes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BriefAfricanBondMarkets2026Route: typeof BriefAfricanBondMarkets2026Route
  BriefEastAfricaInfrastructureParadoxRoute: typeof BriefEastAfricaInfrastructureParadoxRoute
  BriefSignalFromTheStreetRoute: typeof BriefSignalFromTheStreetRoute
  BriefTheRefineryThatCouldRewireAfricanFinanceRoute: typeof BriefTheRefineryThatCouldRewireAfricanFinanceRoute
  InvestigationsDangoteEffectRefineryRoute: typeof InvestigationsDangoteEffectRefineryRoute
  InvestigationsGreatEthiopianDamNegotiationsRoute: typeof InvestigationsGreatEthiopianDamNegotiationsRoute
  Weekend48HoursInKigaliRoute: typeof Weekend48HoursInKigaliRoute
  WeekendElectricHumOfCuriousPeopleRoute: typeof WeekendElectricHumOfCuriousPeopleRoute
  WeekendLibraryOfLostFortunesRoute: typeof WeekendLibraryOfLostFortunesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend/library-of-lost-fortunes': {
      id: '/weekend/library-of-lost-fortunes'
      path: '/weekend/library-of-lost-fortunes'
      fullPath: '/weekend/library-of-lost-fortunes'
      preLoaderRoute: typeof WeekendLibraryOfLostFortunesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend/electric-hum-of-curious-people': {
      id: '/weekend/electric-hum-of-curious-people'
      path: '/weekend/electric-hum-of-curious-people'
      fullPath: '/weekend/electric-hum-of-curious-people'
      preLoaderRoute: typeof WeekendElectricHumOfCuriousPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend/48-hours-in-kigali': {
      id: '/weekend/48-hours-in-kigali'
      path: '/weekend/48-hours-in-kigali'
      fullPath: '/weekend/48-hours-in-kigali'
      preLoaderRoute: typeof Weekend48HoursInKigaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/great-ethiopian-dam-negotiations': {
      id: '/investigations/great-ethiopian-dam-negotiations'
      path: '/investigations/great-ethiopian-dam-negotiations'
      fullPath: '/investigations/great-ethiopian-dam-negotiations'
      preLoaderRoute: typeof InvestigationsGreatEthiopianDamNegotiationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/dangote-effect-refinery': {
      id: '/investigations/dangote-effect-refinery'
      path: '/investigations/dangote-effect-refinery'
      fullPath: '/investigations/dangote-effect-refinery'
      preLoaderRoute: typeof InvestigationsDangoteEffectRefineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/the-refinery-that-could-rewire-african-finance': {
      id: '/brief/the-refinery-that-could-rewire-african-finance'
      path: '/brief/the-refinery-that-could-rewire-african-finance'
      fullPath: '/brief/the-refinery-that-could-rewire-african-finance'
      preLoaderRoute: typeof BriefTheRefineryThatCouldRewireAfricanFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/signal-from-the-street': {
      id: '/brief/signal-from-the-street'
      path: '/brief/signal-from-the-street'
      fullPath: '/brief/signal-from-the-street'
      preLoaderRoute: typeof BriefSignalFromTheStreetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/east-africa-infrastructure-paradox': {
      id: '/brief/east-africa-infrastructure-paradox'
      path: '/brief/east-africa-infrastructure-paradox'
      fullPath: '/brief/east-africa-infrastructure-paradox'
      preLoaderRoute: typeof BriefEastAfricaInfrastructureParadoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/african-bond-markets-2026': {
      id: '/brief/african-bond-markets-2026'
      path: '/brief/african-bond-markets-2026'
      fullPath: '/brief/african-bond-markets-2026'
      preLoaderRoute: typeof BriefAfricanBondMarkets2026RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BriefAfricanBondMarkets2026Route: BriefAfricanBondMarkets2026Route,
  BriefEastAfricaInfrastructureParadoxRoute:
    BriefEastAfricaInfrastructureParadoxRoute,
  BriefSignalFromTheStreetRoute: BriefSignalFromTheStreetRoute,
  BriefTheRefineryThatCouldRewireAfricanFinanceRoute:
    BriefTheRefineryThatCouldRewireAfricanFinanceRoute,
  InvestigationsDangoteEffectRefineryRoute:
    InvestigationsDangoteEffectRefineryRoute,
  InvestigationsGreatEthiopianDamNegotiationsRoute:
    InvestigationsGreatEthiopianDamNegotiationsRoute,
  Weekend48HoursInKigaliRoute: Weekend48HoursInKigaliRoute,
  WeekendElectricHumOfCuriousPeopleRoute:
    WeekendElectricHumOfCuriousPeopleRoute,
  WeekendLibraryOfLostFortunesRoute: WeekendLibraryOfLostFortunesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
